"use strict";
exports.__esModule = true;
var Cuadrado_1 = require("./Cuadrado");
var Rectangulo_1 = require("./Rectangulo");
var Rombo_1 = require("./Rombo");
var Romboide_1 = require("./Romboide");
var Trapecio_1 = require("./Trapecio");
var Triangulo_1 = require("./Triangulo");
var miCuadrado1 = new Cuadrado_1["default"](40, 40);
console.log(miCuadrado1.calcularArea());
console.log(' ');
var miCuadrado2 = new Cuadrado_1["default"](40, 30);
console.log(miCuadrado2.calcularArea());
console.log(' ');
var miRectangulo1 = new Rectangulo_1["default"](32, 67);
console.log(miRectangulo1.calcularArea());
console.log(' ');
var miRectangulo2 = new Rectangulo_1["default"](32, 32);
console.log(miRectangulo2.calcularArea());
console.log(' ');
var miRombo = new Rombo_1["default"](23, 97);
console.log(miRombo.calcularArea());
console.log(' ');
var miRomboide = new Romboide_1["default"](50, 77);
console.log(miRomboide.calcularArea());
console.log(' ');
var miTrapecio1 = new Trapecio_1["default"](40, 77, 104);
console.log(miTrapecio1.calcularArea());
console.log(' ');
var miTrapecio2 = new Trapecio_1["default"](40, 77, 40);
console.log(miTrapecio2.calcularArea());
console.log(' ');
var miTriangulo = new Triangulo_1["default"](64, 83);
console.log(miTriangulo.calcularArea());
console.log(' ');
